apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  labels:
    backstage.io/kubernetes-id: postgres
  name: postgres
  description: postgres
  annotations:
    backstage.io/kubernetes-label-selector: "app=postgres"
spec:
  type: service
#spec:
#  kubernetes:
#    selector:
#      matchLabels:
#        app: postgres