apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    tektonci/build-namespace: sample-go-application-build
    tektonci/pipeline-label-selector: 'pipeline.jquad.rocks/git.repository.branch.name=test-pr-9'
  name: jquad-microservice
  description: JQuad Microservice
spec:
  type: service
  lifecycle: production
  owner: user:guest
